// Copyright 2006-2022 ClickTale Ltd., US Patent Pending

window.ClickTaleGlobal = window.ClickTaleGlobal || {};
window.ClickTaleSettings = window.ClickTaleSettings || {};

ClickTaleGlobal.init = ClickTaleGlobal.init || {};
ClickTaleGlobal.scripts = ClickTaleGlobal.scripts || {};

ClickTaleGlobal.scripts.filter = ClickTaleGlobal.scripts.filter || (function () {
	var recordingThreshold = Math.random() * 100;

	return {
		isRecordingApproved: function(percentage) {
			return recordingThreshold <= percentage;
		}
	}
})();
	
		
// Copyright 2006-2022 ClickTale Ltd., US Patent Pending
// PID: 53334



/*browsers exclusion start*/ ClickTaleSettings.PTC.doOnlyWhen = function (toDoHandler, toCheckHandler, interval, times, failHandler) {
            if ((!toDoHandler) || (!toCheckHandler)) return;
            if (typeof interval == 'undefined') interval = 1000;
            if (typeof times == 'undefined') times = 20;
        
            if (--times < 0) {
                if (typeof failHandler === 'function') {
                    failHandler();
                }
                return;
            }
            if (toCheckHandler()) {
                toDoHandler();
                return;
            }
        
            setTimeout(function () { ClickTaleSettings.PTC.doOnlyWhen(toDoHandler, toCheckHandler, interval, times, failHandler); }, interval);
        }
        ClickTaleSettings.PTC.doOnlyWhen(function () { 
            if (window.ClickTaleSettings.PTC.okToRunPCC) { 
                (function(){
                    window.ClickTaleSettings = window.ClickTaleSettings || {};
                    ClickTaleSettings.PTC = ClickTaleSettings.PTC || {};
                    ClickTaleSettings.PTC.originalPCCLocation = 'P1_PID53334';
                    
                    function d(a,b,c,e,k){a&&b&&("undefined"==typeof c&&(c=1E3),"undefined"==typeof e&&(e=20),0>--e?"function"===typeof k&&k():b()?a():setTimeout(function(){d(a,b,c,e,k)},c))};function g(a,b){b||(b=document);return b instanceof Element||b instanceof Document?Array.prototype.slice.call(b.querySelectorAll(a)):"string"===typeof b?g(a,document.querySelectorAll(b)):Array.isArray(b)||b instanceof HTMLCollection||b instanceof NodeList?Array.prototype.reduce.call(b,function(c,e){return c.concat(Array.prototype.slice.call(e.querySelectorAll(a)))},[]):[]}
function n(a,b){if(a&&a.nodeType&&9===a.nodeType)return!1;var c=Element.prototype;n=function(e,k){return e&&document.documentElement.contains(e)?n.b.call(e,k):!1};n.b=c.webkitMatchesSelector||c.mozMatchesSelector||c.msMatchesSelector||c.matches;return n(a,b)}function p(a,b){p=Element.prototype.closest?function(c,e){return c&&c instanceof Element?Element.prototype.closest.call(c,e):null}:function(c,e){for(;c&&!n(c,e);)c=c.parentElement;return c};return p(a,b)};var r=!1,aa=Object.defineProperty&&Object.defineProperty({},"passive",{get:function(){r=!0}});document.addEventListener("test",function(){},aa);var t=r?{passive:!0,capture:!0}:!0,u=r?{passive:!0,capture:!1}:!1;
function v(a){function b(){2==++c&&a()}if(!~v.b.indexOf(a)){v.b.push(a);var c=0;ba(b);if("function"==typeof ClickTaleIsRecording&&!0===ClickTaleIsRecording())b();else{var e=window.ClickTaleOnRecording||function(){};window.ClickTaleOnRecording=function(){b();return e.apply(this,arguments)}}}}v.b=[];function ba(a){function b(){c||(c=!0,a())}var c=!1;"loading"!=document.readyState?b():document.addEventListener&&document.addEventListener("DOMContentLoaded",b,!1)}
function x(a,b,c,e,k){if("string"===typeof b&&-1!=b.indexOf(" "))return b.split(/\s+/).forEach(function(m){return x(a,m,c,e,k)}),a;if("string"===typeof a)Array.prototype.forEach.call(document.querySelectorAll(a),function(m){x(m,b,c,e,k)});else if(a instanceof Array||a instanceof NodeList)Array.prototype.forEach.call(a,function(m){x(m,b,c,e,k)});else{var f="";"string"==typeof c&&("mouseenter"==b?(b="mouseover",f="mouseenter"):"mouseleave"==b&&(b="mouseout",f="mouseleave"));a.addEventListener(b,function(m,
h,l,q,w,B){return function(V){if("function"===typeof l)l.apply(this,arguments),w&&m.removeEventListener(h,arguments.callee,t);else{var N=V.relatedTarget,y=p(V.target,l);y&&m.compareDocumentPosition(y)&Node.DOCUMENT_POSITION_CONTAINED_BY&&("mouseenter"==B||"mouseleave"==B?N&&(N==y||y.compareDocumentPosition(N)&Node.DOCUMENT_POSITION_CONTAINED_BY)||q.apply(y,arguments):q.apply(y,arguments),w&&m.removeEventListener(h,arguments.callee,t))}}}(a,b,c,e,k,f),t)}return a}
function ca(a,b){document.addEventListener("mouseup",function(c){a===c.target&&b();document.removeEventListener("mouseup",arguments.callee,u)},u)}function da(a,b){document.addEventListener("mouseup",function(c){a===c.target&&b();document.removeEventListener("mouseup",arguments.callee,t)},t)}
function ea(a,b){function c(e){document.removeEventListener("touchend",arguments.callee,u);a===e.target&&b()}document.addEventListener("touchend",c,u);document.addEventListener("touchmove",function(e){document.removeEventListener("touchmove",arguments.callee,u);document.removeEventListener("touchend",c,u)},u)}
function fa(a,b){function c(e){document.removeEventListener("touchend",arguments.callee,t);a===e.target&&b()}document.addEventListener("touchend",c,t);document.addEventListener("touchmove",function(e){document.removeEventListener("touchmove",arguments.callee,t);document.removeEventListener("touchend",c,t)},t)}function z(a,b){var c=A();c&&(z=c.m?ea:ca,z(a,b))}function C(a,b){var c=A();c&&(C=c.m?fa:da,C(a,b))};function D(a){if(window.CSS&&"function"===typeof window.CSS.escape)D=function(e){return window.CSS.escape.call(window.CSS,e)};else{var b=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\x80-\uFFFF\w-]/g,c=function(e,k){return k?"\x00"===e?"\ufffd":e.slice(0,-1)+"\\"+e.charCodeAt(e.length-1).toString(16)+" ":"\\"+e};D=function(e){return e.replace(b,c)}}return D(a)}function E(a){return btoa(encodeURIComponent(a).replace(/%([0-9A-F]{2})/g,function(b,c){return String.fromCharCode(+("0x"+c))}))};function ha(a){window._uxa=window._uxa||[];window._uxa.push.apply(window._uxa,arguments)};function F(){var a=!1;if(window.ClickTaleMonitor&&"function"===typeof window.ClickTaleMonitor.isMonitoring&&window.ClickTaleMonitor.isMonitoring())a=!0;else if(window.ClickTaleMonitor){var b=window.ClickTaleMonitor&&ClickTaleMonitor.Settings&&"function"==typeof ClickTaleMonitor.Settings.get?ClickTaleMonitor.Settings.get():null;if(b)b.onStart(function(){F.b=!0})}else return d(F,function(){return!!window.ClickTaleMonitor},1E3,10),!1;F=function(){return F.b};F.b=a;return F.b}F.b=!1;F();function ia(){var a=G.toString();"function"===typeof ClickTaleField&&ClickTaleField("isMobile",a)}function H(a){"function"===typeof ClickTaleExec&&ClickTaleExec(a)}function I(){"function"===typeof ClickTaleStop&&ClickTaleStop()}function J(a,b){"function"===typeof ClickTaleEvent&&(b?!0!==J.b[a]&&(J.b[a]=!0,ClickTaleEvent(a)):ClickTaleEvent(a))}J.b={};
function K(a,b){a&&"object"==typeof a&&"string"==typeof b&&(window.ClickTaleContext&&-1!=document.referrer.indexOf(location.hostname)&&window.parent.ct&&window.parent.ct.ElementAddressing&&"function"===typeof window.parent.ct.ElementAddressing.forceSetCustomElementID?window.parent.ct.ElementAddressing.forceSetCustomElementID(a,b):(window.ClickTaleContext||"function"!==typeof ClickTaleSetCustomElementID||-1==ClickTaleSetCustomElementID.toString().indexOf("duplicate registration of custom id")?window.ClickTaleSetCustomElementID=
window.ClickTaleSetCustomElementID||function(c,e){c.ClickTale=c.ClickTale||{};c.ClickTale.CustomID=e}:K=function(c,e){c.ClickTale=c.ClickTale||{};c.ClickTale.CustomID=e},window.ClickTaleSetCustomElementID(a,b)))}
function ja(){Array.prototype.forEach.call(document.querySelectorAll('[id]:not([id=""])'),function(a){if(!n(a,'input[type="hidden"], script')){var b=a.getAttribute("id");b.match(/(?:\r|\n)/)&&"function"===typeof ClickTaleNote&&ClickTaleNote("ctlib.api.SetCustomElementIdDuplicates: ids with line break found!");a=document.querySelectorAll('[id="'+D(b)+'"]');var c=L;1<a.length&&!c[b]&&(c[b]=!0,Array.prototype.forEach.call(a,function(e,k){K(e,b.replace(/(\r|\n|\r\n|\s+)+/g,"_").replace(/\W/g,"_")+"_"+
k)}))}})}var L={};function M(a,b){"function"===typeof ClickTaleLogical&&(J.b={},L={},O.b&&O.b instanceof P&&O.b.clear(),b?ClickTaleLogical(a,b):ClickTaleLogical(a))}function A(){if("function"===typeof ClickTaleDetectAgent){var a=ClickTaleDetectAgent();if(a)return A=function(){return a},A()}return null}function Q(a){if("function"===typeof ClickTaleRegisterTouchAction){var b=a.getBoundingClientRect();ClickTaleRegisterTouchAction(a,b.left+document.body.scrollLeft,b.top+document.body.scrollTop)}}
function ka(){if("boolean"!=typeof R){var a=A();a&&(R=!!a.m)}if(!b){var b="mousedown";R&&(b="touchstart")}a="img, a, button, textarea, input, select";R&&(a+=", label[for]");x(document,b,a,function(c){var e=c.target,k=this;if(R)if(n(this,"label[for]"))C(e,function(h){return function(){var l,q;(l=h.getAttribute("for"))&&(q=document.getElementById(l))&&Q(q)}.bind(k)}(e,c));else{var f=-1,m=function(h){clearTimeout(f);document.removeEventListener("touchstart",arguments.callee,u);C(e,function(l){return function(){function q(B){document.removeEventListener("touchend",
arguments.callee,u);clearTimeout(w)}var w=-1;document.addEventListener("touchend",q,u);w=setTimeout(function(){document.removeEventListener("touchend",q,u);Q(l)},50)}.bind(k)}(e,c))};document.addEventListener("touchstart",m,u);f=setTimeout(function(){document.removeEventListener("touchstart",m,u);Q(e)},50)}else C(e,function(h,l){return function(){function q(B){B.target===h&&(S=!0);document.removeEventListener("click",arguments.callee,!0);clearTimeout(w)}var w=setTimeout(function(){S||"function"===
typeof window.ClickTaleRegisterElementAction&&ClickTaleRegisterElementAction("click",l);document.removeEventListener("click",q,!0);S=void 0},200);document.addEventListener("click",q,!0)}.bind(k)}(e,c))})}var R,S;
function T(){var a=la,b=document.location.href,c=500;if(T.b){T.b=!1;var e=e||400;"number"==typeof c&&(e=c,c="");b=b||document.location.href;I();window.ClickTaleIncludedOnDOMReady=!0;window.ClickTaleIncludedOnWindowLoad=!0;"function"===typeof ClickTaleUploadPage&&ClickTaleUploadPage(void 0,void 0);M(b,c);d(a,ClickTaleIsRecording,1E3,2);setTimeout(function(){T.b=!0},e)}}T.b=!0;
function P(){this.f=!1;this.b="";this.init=function(a){this.f||(this.f=!0,document.addEventListener("input",this.g,t));this.h(a);this.b=this.b?this.b+","+a:a};this.g=function(a){a=a.target;if(n(a,this.b)){var b=g(this.b).indexOf(a);H("document.querySelectorAll('"+this.b+"')["+b+"].value = Base64Decode('"+E(a.value)+"');")}}.bind(this);this.h=function(a){var b="";g(a).forEach(function(c,e){b+="document.querySelectorAll('"+a+"')["+e+"].value = Base64Decode('"+E(c.value)+"'); "});b&&H(b)};this.clear=
function(){document.removeEventListener("input",this.g,t);this.f=!1;this.b=""}}function O(a){O.b=O.b||new P;O.b.init(a)}O.b=null;var U=J;function W(a,b){return a instanceof Element?b instanceof Element?a===b:n(a,b):!1}var X=p,ma=z;var Y=document.location.pathname.toLowerCase(),G=!1,Z="on",na="/us/en-us/company/sustainability/climate-action.html /us/en-us/company/sustainability/ethics-compliance.html /us/en-us/company/sustainability/information-security.html /us/en-us/company/sustainability/positive-impact-products.html /us/en-us/company/sustainability/research-development-innovation.html /us/en-us/company/sustainability/health-safety.html /us/en-us/company/sustainability/talent-management.html /us/en-us/company/sustainability/inclusion-diversity.html /us/en-us/company/sustainability/waste-reduction.html /us/en-us/company/sustainability/water-use.html /us/en-us/company/sustainability/community-involvement.html".split(" ");
function oa(a){var b;d(function(){ha(["trackDynamicVariable",{key:a,value:b}])},function(){var c=window.dataLayer;b=!!c&&c[a];return!!b},250,10)}
function la(){ja();d(function(){if(window.dataLayer){for(var c=window.dataLayer,e=0;e<c.length;e++)c[e].eventAction&&U("Onload | Data Layer | Event Action | "+c[e].eventAction.trim());c.pageType&&U("Onload | Data Layer | Page Type | "+c.pageType.trim());c.loginState&&U("Onload | Data Layer | Login State | "+c.loginState.trim());c.productFamily&&U("Onload | Data Layer | Product Family | "+c.productFamily.trim());c.productCategory&&U("Onload | Data Layer | Product Category | "+c.productCategory.trim())}},
function(){return!!window.dataLayer},250,40);document.querySelectorAll(".search-results__no-result").length&&U("Onload | Search Result Empty");-1!=na.indexOf(Y)&&U("Onload | Sustainability | Topic Page");for(var a=["country","language","sectorBusiness","siteSearchFacets"],b=0;b<a.length;b++)oa(a[b])}
function pa(){if(!window.ClickTaleFirstPCCGo){window.ClickTaleFirstPCCGo=!0;var a=A();a&&(G=a.m,ia());"function"!=typeof jQuery.fn.on&&(Z="delegate");la();x(document,"keyup","#site-search-box",function(c){U("Action | Type in Search",!0);13==c.keyCode&&X(this,"#site-search-box")&&U("Action | Search Enter")});window.ga&&window.ga.getAll&&"function"==typeof window.ga.getAll&&(a=window.ga.getAll())&&0<a.length&&""!=a[0].get("name")&&"function"==typeof ClickTaleGetUID&&null!=ClickTaleGetUID()&&window.ga(a[0].get("name")+
".send","event","ClickTale","UID",ClickTaleGetUID().toString(),{dimension3:ClickTaleGetUID().toString(),nonInteraction:1});a=G?"touchstart":"mousedown";var b="";a="on"===Z?[a,'.eaton-search__submit,ul>li.module-tabs__list-item,#content-type li.faceted-navigation__list-item,li.faceted-navigation__list-item,.results-list-submodule__link-item-link,.global-filter-search__input,button[data-load-more],#dSortFacets,ul.dropdown-menu a.faceted-navigation-header__sort-link,.results-list-submodule--type-family a[href*="catalog"],.results-list-submodule--type-news-and-insights a[href*="NewsEvents"],.results-list-submodule--type-news-and-insights a[href*="news-insights"],.results-list-submodule--type-news-and-insights a[href*=".pdf"],.results-list-submodule--type-resources a[href*="Resources"],.results-list-submodule--type-resources a[href*="content"],.results-list-submodule--type-resources a[href*=".pdf"],.eaton-topic-link--white a,a[href*="/documents/content/pct"],feature-block--left a.feature-block__cta,.feature-block--right a.feature-block__cta,a[href*="internet-of-things.html"],a.eaton-topic-link__button[href*="/MicrogridEnergySystem/index.htm"],a[href*="/content/dam/eaton/company/sustainability/files/"],a[href*="/Sustainability-Metrics.pdf"],.eaton-topic-link--grey a,a[href*="these-5-companies-are-leading-the-charge-on-recycling"],.eaton-topic-link--grey a[href*="ehs-policy.html"],.eaton-topic-link--grey a[href*="newmap2/index.html"],.feature-block--with-image a[href*="climate-action.html"],a[href*="from-our-chairman.html"],.eaton-topic-link--grey a[href*="climate-action.html"],.feature-block--with-image a[href*="stakeholder.html"],.feature-block--right a[href*="how-me-make-what-matters-work.html"],.feature-block--left a[href*="how-me-make-what-matters-work.html"],a[href*="supply-chain-management.html"],.feature-block--left a[href*="privacy-cookies-and-data-protection.html"],.feature-block--left a[href*="ethics-compliance.html"],a[href*="sustainability/files/Eaton"]']:
['.eaton-search__submit,ul>li.module-tabs__list-item,#content-type li.faceted-navigation__list-item,li.faceted-navigation__list-item,.results-list-submodule__link-item-link,.global-filter-search__input,button[data-load-more],#dSortFacets,ul.dropdown-menu a.faceted-navigation-header__sort-link,.results-list-submodule--type-family a[href*="catalog"],.results-list-submodule--type-news-and-insights a[href*="NewsEvents"],.results-list-submodule--type-news-and-insights a[href*="news-insights"],.results-list-submodule--type-news-and-insights a[href*=".pdf"],.results-list-submodule--type-resources a[href*="Resources"],.results-list-submodule--type-resources a[href*="content"],.results-list-submodule--type-resources a[href*=".pdf"],.eaton-topic-link--white a,a[href*="/documents/content/pct"],feature-block--left a.feature-block__cta,.feature-block--right a.feature-block__cta,a[href*="internet-of-things.html"],a.eaton-topic-link__button[href*="/MicrogridEnergySystem/index.htm"],a[href*="/content/dam/eaton/company/sustainability/files/"],a[href*="/Sustainability-Metrics.pdf"],.eaton-topic-link--grey a,a[href*="these-5-companies-are-leading-the-charge-on-recycling"],.eaton-topic-link--grey a[href*="ehs-policy.html"],.eaton-topic-link--grey a[href*="newmap2/index.html"],.feature-block--with-image a[href*="climate-action.html"],a[href*="from-our-chairman.html"],.eaton-topic-link--grey a[href*="climate-action.html"],.feature-block--with-image a[href*="stakeholder.html"],.feature-block--right a[href*="how-me-make-what-matters-work.html"],.feature-block--left a[href*="how-me-make-what-matters-work.html"],a[href*="supply-chain-management.html"],.feature-block--left a[href*="privacy-cookies-and-data-protection.html"],.feature-block--left a[href*="ethics-compliance.html"],a[href*="sustainability/files/Eaton"]',
a];jQuery(document)[Z](a[0],a[1],function(c){var e=c.target;jQuery(c);var k=jQuery(this),f=this;ma(e,function(m,h){return function(){W(f,".eaton-search__submit")&&U("Action | Search Enter");if(-1<Y.indexOf("/site-search"))if(W(f,"ul>li.module-tabs__list-item")){U("Action | Search Results | Any Tab");var l=h.textContent.trim();b=l;-1<b.indexOf("(")&&(l=b.substr(0,b.indexOf("(")-1));l&&U("Action | Search Results | "+l+" Tab")}else if(X(f,"#content-type li.faceted-navigation__list-item")){if(b=jQuery(h).closest("div[id]").prev("button.faceted-navigation__header").text().trim())U("Action | Search Results | "+
b+" Filters"),b=jQuery(h).parents("li").find("span>bdi").text().trim(),U("Action |Search Results |  Content Type | "+b)}else X(f,"li.faceted-navigation__list-item")?(b=jQuery(h).closest("div[id]").prev("button.faceted-navigation__header").text().trim())&&U("Action | Search Results | "+b+" Filters"):W(f,".results-list-submodule__link-item-link")?(b=h.textContent.trim())&&U("Action | Search Results | Select Product "+b):W(f,".global-filter-search__input")?U("Action | Search Results | Search Filter"):
W(f,"button[data-load-more]")?U("Action | Search Results | Load More"):W(f,".results-list-submodule--type-family a[href*='catalog']")?U("Action | Search Results | Select Product"):X(f,".results-list-submodule--type-news-and-insights a[href*='NewsEvents'],.results-list-submodule--type-news-and-insights a[href*='news-insights'],.results-list-submodule--type-news-and-insights a[href*='.pdf']")?U("Action |Search Results | Select NewsEvents"):W(f,".results-list-submodule--type-resources a[href*='Resources'],.results-list-submodule--type-resources a[href*='content'],.results-list-submodule--type-resources a[href*='.pdf']")?
U("Action | Search Results | Select Resources"):W(f,"#dSortFacets")?U("Action | Search Results | Sort By"):X(f,"ul.dropdown-menu a.faceted-navigation-header__sort-link")&&(b=h.textContent.trim(),U("Action | Search Results | Sort By | "+b));-1<Y.indexOf("/content/eaton/us/en-us/company/sustainability.html.html")?W(f,".feature-block--with-image a[href*='climate-action.html']")?U("A | Sustainability | GHG emissions"):W(f,"a[href*='from-our-chairman.html']")?U("A | Sustainability | Read the statement"):
W(f,".eaton-topic-link--grey a[href*='climate-action.html']")?U("A | Sustainability | View responses"):W(f,".feature-block--with-image a[href*='stakeholder.html']")?U("A | Sustainability | Key issues"):W(f,".feature-block--right a[href*='how-me-make-what-matters-work.html']")?U("A | Sustainability | stakeholder engagement"):W(f,".feature-block--left a[href*='how-me-make-what-matters-work.html']")?U("A | Sustainability | stakeholder Governance"):W(f,"a[href*='supply-chain-management.html']")&&U("A | Sustainability | Supply chain"):
-1<Y.indexOf("/us/en-us/company/sustainability/climate-action.html")?W(f,".eaton-topic-link--white a")?U("A | Climate Action | CDP responses"):W(f,".eaton-topic-link--grey a")?U("A | Climate Action | EHS policy"):W(f,"a[href*='/documents/content/pct']")&&U("A | Climate Action | Governance"):-1<Y.indexOf("/us/en-us/company/sustainability/information-security.html")?W(f,".feature-block--left a[href*='privacy-cookies-and-data-protection.html']")?U("A | I & S | Personal data"):W(f,".feature-block--right a.feature-block__cta")?
U("A | I & S | Cybersecurity"):W(f,".feature-block--left a[href*='ethics-compliance.html']")&&U("A | I & S | Ethics"):-1<Y.indexOf("/us/en-us/company/sustainability/research-development-innovation.html")?W(f,"a[href*='internet-of-things.html']")?U("A | R&D | Intelligence"):W(f,"a.eaton-topic-link__button[href*='/MicrogridEnergySystem/index.htm']")&&U("A | R&D | Innovations"):-1<Y.indexOf("/us/en-us/company/sustainability/inclusion-diversity.html")?W(f,"a[href*='/Sustainability-Metrics.pdf']")&&h&&
h.closest(".row.eaton-topic-link__row")&&h.closest(".row.eaton-topic-link__row").querySelector("h3")?-1<h.closest(".row.eaton-topic-link__row").querySelector("h3").textContent.indexOf("global")?U("A | Inclusion | Global Employment"):-1<h.closest(".row.eaton-topic-link__row").querySelector("h3").textContent.indexOf("supplier")?U("A | Inclusion | Suppliers"):-1<h.closest(".row.eaton-topic-link__row").querySelector("h3").textContent.indexOf("Gender")&&U("A | Inclusion | Gender Pay Gap"):W(f,"a[href*='sustainability/files/Eaton']")&&
h&&h.closest(".row.eaton-topic-link__row")&&h.closest(".row.eaton-topic-link__row").querySelector("h3")&&-1<h.closest(".row.eaton-topic-link__row").querySelector("h3").textContent.indexOf("Gender")&&U("A | Inclusion | Gender Pay Gap"):-1<Y.indexOf("/us/en-us/company/sustainability/waste-reduction.html")&&(W(f,".eaton-topic-link--grey a[href*='ehs-policy.html']")?U("A | Waste | EHS policy"):W(f,"a[href*='/Sustainability-Metrics.pdf']")?U("A | Waste | Waste and landfill"):W(f,"a[href*='these-5-companies-are-leading-the-charge-on-recycling']")&&
U("A | Waste | Waste and landfill recognition"),W(f,".eaton-topic-link--grey a[href*='newmap2/index.html']")&&U("A | Waste | Zero Waste"))}.bind(m[0])}(k,e,c))});"/poweraccess"==Y&&(jQuery(document).on("mousedown","#assetButton",function(){U("Action | PowerAccess | Clicks Dont be left behind")}),jQuery(document).on("mousedown",".cta_html a:eq(0)",function(){U("Action | PowerAccess | Challenges Panel | Clicks See how we do it")}),jQuery(document).on("mousedown",".cta_html a:eq(1)",function(){U("Action | PowerAccess | IOT Panel | Clicks Read More")}),
jQuery(document).on("mousedown",".cta_html a:eq(2)",function(){U("Action | PowerAccess | Case Study Panel | Clicks Read More")}));"/eaton/productsservices/electrical/markets/hvacr/eatonhvach-max/index.htm"==Y&&(jQuery(".orangebox.downloadbutton.aemisfun").mousedown(function(){d(function(){setTimeout(function(){T();U("Onload | Electrical Markets HVAC | Lead Gen Form")},500)},function(){return jQuery("#ELOQUAFORM").is(":visible")?!0:!1},250,40)}),jQuery(".SubmitESTR").mousedown(function(){U("Action | White Papaer | Submit Clicked");
var c=document.querySelector("#ELOQUAFORM");"function"===typeof ClickTaleRegisterFormSubmit&&ClickTaleRegisterFormSubmit(c);"function"===typeof ClickTaleRegisterFormSubmitSent&&ClickTaleRegisterFormSubmitSent(c)}));"/eaton/productsservices/electrical/markets/hvacr/eatonhvach-max/thankyou/index.htm"==Y&&"function"==typeof ClickTaleRegisterFormSubmitSuccess&&ClickTaleRegisterFormSubmitSuccess();jQuery("#searchImg").click(function(){U("Action | Site Wide | Activates Search")});jQuery("a[href='/Eaton/CustomerSupport/index.htm']").click(function(){U("Action | Site Wide | Clicks Customer Support")});
jQuery("#SearchTerm").keyup(function(c){var e=jQuery(this).val();H('jQuery("SearchTerm").val("'+e+'");');"13"==c.keyCode&&U("Action | Site Wide | Activates Search")});-1<document.location.href.toLowerCase().indexOf("productsservices")&&0<jQuery(".ui-tabs-nav").length&&(U("Onload | PDP"),a=jQuery(".ui-tabs-nav .ui-tabs-selected").text(),0<jQuery("#right .kpiSpan a").length&&jQuery("#right .kpiSpan a").click(function(){var c=jQuery(this).text().trim();U("Action | PDP | Right Panel | Clicks   "+c);U("Action | PDP | Clicks in Right Panel")}),
U("Onload | PDP | "+a),jQuery(".resizeme").click(function(){U("Action | PDP | Clicks Anywhere in Product Description Text")}),jQuery(".Submitbutton").click(function(){U("Action | PDP | Clicks on Inquiries Submit")}),jQuery("#topImage img").click(function(){U("Action | PDP | Clicks Product Image")}),jQuery(".ui-tabs-nav>li>a").click(function(){var c=jQuery(this).text().trim();U("Action | PDP | Tabbed Content | Clicks "+c);U("Action | PDP | Clicks on Tabs");setTimeout(function(){I();ClickTaleUploadPage();
window.ClickTaleIncludedOnWindowLoad=!0;window.ClickTaleIncludedOnDomReady=!0;M(document.location.href);var e=jQuery(".ui-tabs-nav .ui-tabs-selected").text();U("Onload | PDP | "+e)},500)}));-1<document.location.href.toLowerCase().indexOf("filtration")&&0<jQuery(".ui-tabs-nav").length&&(U("Onload | Filtration PDP"),a=jQuery(".ui-tabs-nav .ui-tabs-selected").text(),U("Onload | Filtration PDP | "+a),jQuery(".kpiDesc:eq(0) a").click(function(){U("Action | Filtration PDP | Clicks on Contact Us")}),jQuery(".dynamictabcontent:eq(0)>a").click(function(){U("Action | Filtration PDP | Downloads PDF")}),
jQuery(".submit-button").click(function(){U("Action | Filtration PDP | Clicks on Inquiries Submit")}),jQuery(".ui-tabs-nav>li>a").click(function(){var c=jQuery(this).text().trim();U("Action | Filtration PDP | "+c);U("Action | Filtration PDP | Clicks on Any of the Tabs ");setTimeout(function(){I();ClickTaleUploadPage();window.ClickTaleIncludedOnWindowLoad=!0;window.ClickTaleIncludedOnDomReady=!0;M(document.location.href);var e=jQuery(".ui-tabs-nav .ui-tabs-selected").text();U("Onload | Filtration PDP | "+
e)},500)}));-1<document.location.href.toLowerCase().indexOf("2016_es_us_cpcd_solutions_drives")&&0<jQuery("#sidebar").length&&(U("Onload | Campaign Landing Page \u2013 Drives"),U("Onload | Campaign Landing Page \u2013 Product Type"),jQuery("#sidebar .module:eq(3)").click(function(){U("Action | Campaign Landing Page | Clicks on Featured Product")}),jQuery("a[title='Click to download']").click(function(){U("Action | Cmpaign Landing Pages | Clicks Download");U("Action | Campaign Landing Page  - Drivers | Clicks Download (Left)\u201d")}));
-1<document.location.href.toLowerCase().indexOf("2016_es_us_cpcd_solutions_contactors")&&0<jQuery("#sidebar").length&&(U("Onload | Campaign Landing Page \u2013 Contractors"),U("Onload | Campaign Landing Page \u2013 Product Type"),jQuery("#sidebar .module:eq(3)").click(function(){U("Action | Campaign Landing Page | Clicks on Featured Product")}),jQuery("a[title='Click to download']").click(function(){U("Action | Cmpaign Landing Pages | Clicks Download");U("Action | Campaign Landing Page  - Contractors | Clicks Download (Left)\u201d")}));
-1<document.location.href.toLowerCase().indexOf("2016_es_us_cpcd_solutions_hvac")&&0<jQuery("#sidebar").length&&(U("Onload | Campaign Landing Page \u2013 HVAC"),U("Onload | Campaign Landing Page \u2013 Segment Type"),jQuery("#sidebar .module:eq(3)").click(function(){U("Action | Campaign Landing Page | Clicks on Featured Product")}),jQuery("a[title='Click to download']").click(function(){U("Action | Cmpaign Landing Pages | Clicks Download");U("Action | Campaign Landing Page  - HVAC | Clicks Download (Left)\u201d")}));
-1<document.location.href.toLowerCase().indexOf("2016_es_us_cpcd_solutions_mhc")&&0<jQuery("#sidebar").length&&(U("Onload | Campaign Landing Page \u2013 MHC"),U("Onload | Campaign Landing Page \u2013 Segment Type"),jQuery("#sidebar .module:eq(3)").click(function(){U("Action | Campaign Landing Page | Clicks on Featured Product")}),jQuery("a[title='Click to download']").click(function(){U("Action | Cmpaign Landing Pages | Clicks Download");U("Action | Campaign Landing Page  - MHC | Clicks Download (Left)\u201d")}));
-1<document.location.href.toLowerCase().indexOf("2016_es_us_cpcd_solutions_pic")&&0<jQuery("#sidebar").length&&(U("Onload | Campaign Landing Page \u2013 PIC"),U("Onload | Campaign Landing Page \u2013 Segment Type"),jQuery("#sidebar .module:eq(3)").click(function(){U("Action | Campaign Landing Page | Clicks on Featured Product")}),jQuery("a[title='Click to download']").click(function(){U("Action | Cmpaign Landing Pages | Clicks Download");U("Action | Campaign Landing Page  - PIC | Clicks Download (Left)\u201d")}));
-1<document.location.href.toLowerCase().indexOf("2016_es_us_cpcd_solutions_pc")&&0<jQuery("#sidebar").length&&(U("Onload | Campaign Landing Page \u2013 PC"),U("Onload | Campaign Landing Page \u2013 Segment Type"),jQuery("#sidebar .module:eq(3)").click(function(){U("Action | Campaign Landing Page | Clicks on Featured Product")}),jQuery("a[title='Click to download']").click(function(){U("Action | Cmpaign Landing Pages | Clicks Download");U("Action | Campaign Landing Page  - PC | Clicks Download (Left)\u201d")}));
-1<document.location.href.toLowerCase().indexOf("2016_es_us_cpcd")&&0<jQuery("#sidebar").length&&(U("Onload | Campaign Landing Pages - 2016 ES US SPCD Solutions"),jQuery(".button:contains('Download'):visible").click(function(){U("Action | Cmpaign Landing Pages | Clicks Download")}),jQuery(".button:contains('Contact')").click(function(){U("Action | Campaign Landing Pages | Clicks Contact")}),jQuery(".submit").click(function(){U("Action | Campaign Landing Pages | Clicks Sign Up")}));jQuery("#SearchTerm").keyup(function(){var c=
jQuery(this).val();H('jQuery("#SearchTerm").val("'+c+'");')});-1<document.location.href.indexOf("CustomerSupport/SignIn/index.htm")&&jQuery(".resizeme td:eq(1) a").click(function(){U("Action | Clicks on Employee Sign In")})}}v(function(){ka();d(pa,function(){return!window.jQuery||"function"!==typeof jQuery.fn.on&&"function"!==typeof jQuery.fn.delegate?!1:!0},250,40)});
                })();
            } 
        }, function () { return !!(window.ClickTaleSettings && ClickTaleSettings.PTC && typeof ClickTaleSettings.PTC.okToRunPCC != 'undefined'); }, 500, 20);


//Signature:n99HDiv9PT5oootDB+qyPVZv4MMs5dKduagKnrnZXIfw4BefzitRPZd6i4A4+oCXu0VlSKRxnNm6YXsgNhXRZRRnzHVSoXrHs6TQVE2jCrShs/7SoJjEhZdd13Xm5HEj7SGO5CxSFmbMKbUNlpZrjhNi46tPRugTAzjCqf378Ks=